TITLE: The yt Project Blog
TITLE_HTML: The yt Project Blog
TAGLINE: Everything going on with yt
POSTS_PER_PAGE: 10
AUTHOR: The yt Project
#DISQUS: your-disqus-id
TIMEZONE: UTC
#POST_EXT: .rst
FREEZER_BASE_URL: http://blog.yt-project.org/
